name: Publish a new release

permissions:
  contents: write

on:
  push:
    branch: stable
    tags:
    - 'v?[0-9]*'

  workflow_call:
    inputs:
      draft:
        description: 'Draft'
        required: true
        default: false
        type: boolean
      prerelease:
        description: 'Prerelease'
        required: true
        type: boolean

  workflow_dispatch:
    inputs:
      draft:
        description: 'Draft'
        required: true
        default: true
        type: boolean
      prerelease:
        description: 'Prerelease'
        required: true
        default: false
        type: boolean

jobs:
  package_asset:
    name: Build release assets
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: linux
            just_target: package-linux
          - platform: win
            just_target: package-win-all
          - platform: win installer
            just_target: package-win-installer
    steps:
      - name: Install dependencies
        uses: taiki-e/install-action@just

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package asset (${{ matrix.platform }})
        run: just ${{ matrix.just_target }}

      - name: Upload the artifact
        uses: actions/upload-artifact@v4
        with:
          name: packaged_asset-${{ matrix.platform }}
          path: |
            *.zip
            *.exe

  public_mac:
    name: 'Build release assets (mac)'
    uses: ./.github/workflows/build_macos.yml
    secrets: inherit

  publish_release:
    name: Create a GitHub release
    runs-on: ubuntu-latest
    needs:
      - package_asset
      - public_mac

    steps:
      - name: Install dependencies
        uses: taiki-e/install-action@just

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download built game assets
        uses: actions/download-artifact@v4
        with:
          path: artifacts/
          merge-multiple: true

      - name: Generate Changelog
        run: |
          just output-current-changelog > _changes.txt

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: Release ${{ github.ref_name }}
          body_path: _changes.txt
          draft: ${{ inputs.draft }}
          prerelease: ${{ inputs.prerelease }}
          fail_on_unmatched_files: true
          files: |
            artifacts/*
